package cashflowdb;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import cashflowdb.UserInfoDao;
import cashflowdb.FinancialYearDao;
import cashflowdb.InitialBudgetDao;
import cashflowdb.CategoryDao;
import cashflowdb.SourceDao;
import cashflowdb.HowOftenDao;
import cashflowdb.InOutTransactionDao;
import cashflowdb.RepeatTransactionDao;
import cashflowdb.DayInOutSummeryDao;
import cashflowdb.SubscriptionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 5): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 5;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        UserInfoDao.createTable(db, ifNotExists);
        FinancialYearDao.createTable(db, ifNotExists);
        InitialBudgetDao.createTable(db, ifNotExists);
        CategoryDao.createTable(db, ifNotExists);
        SourceDao.createTable(db, ifNotExists);
        HowOftenDao.createTable(db, ifNotExists);
        InOutTransactionDao.createTable(db, ifNotExists);
        RepeatTransactionDao.createTable(db, ifNotExists);
        DayInOutSummeryDao.createTable(db, ifNotExists);
        SubscriptionDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        UserInfoDao.dropTable(db, ifExists);
        FinancialYearDao.dropTable(db, ifExists);
        InitialBudgetDao.dropTable(db, ifExists);
        CategoryDao.dropTable(db, ifExists);
        SourceDao.dropTable(db, ifExists);
        HowOftenDao.dropTable(db, ifExists);
        InOutTransactionDao.dropTable(db, ifExists);
        RepeatTransactionDao.dropTable(db, ifExists);
        DayInOutSummeryDao.dropTable(db, ifExists);
        SubscriptionDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(UserInfoDao.class);
        registerDaoClass(FinancialYearDao.class);
        registerDaoClass(InitialBudgetDao.class);
        registerDaoClass(CategoryDao.class);
        registerDaoClass(SourceDao.class);
        registerDaoClass(HowOftenDao.class);
        registerDaoClass(InOutTransactionDao.class);
        registerDaoClass(RepeatTransactionDao.class);
        registerDaoClass(DayInOutSummeryDao.class);
        registerDaoClass(SubscriptionDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
