package cashflowdb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INITIAL_BUDGET".
 */
public class InitialBudget {

    /** Not-null value. */
    private String bugetID;
    private String moneytype;
    private Double pound;
    private java.util.Date startdate;
    private String comment;

    public InitialBudget() {
    }

    public InitialBudget(String bugetID) {
        this.bugetID = bugetID;
    }

    public InitialBudget(String bugetID, String moneytype, Double pound, java.util.Date startdate, String comment) {
        this.bugetID = bugetID;
        this.moneytype = moneytype;
        this.pound = pound;
        this.startdate = startdate;
        this.comment = comment;
    }

    /** Not-null value. */
    public String getBugetID() {
        return bugetID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBugetID(String bugetID) {
        this.bugetID = bugetID;
    }

    public String getMoneytype() {
        return moneytype;
    }

    public void setMoneytype(String moneytype) {
        this.moneytype = moneytype;
    }

    public Double getPound() {
        return pound;
    }

    public void setPound(Double pound) {
        this.pound = pound;
    }

    public java.util.Date getStartdate() {
        return startdate;
    }

    public void setStartdate(java.util.Date startdate) {
        this.startdate = startdate;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

}
