package cashflowdb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SUBSCRIPTION".
 */
public class Subscription {

    private Long id;
    private java.util.Date subscriptionStartDate;
    private java.util.Date subscriptionEndDate;
    private String adminName;
    private Boolean isSubscribed;
    private String adminPassword;

    public Subscription() {
    }

    public Subscription(Long id) {
        this.id = id;
    }

    public Subscription(Long id, java.util.Date subscriptionStartDate, java.util.Date subscriptionEndDate, String adminName, Boolean isSubscribed, String adminPassword) {
        this.id = id;
        this.subscriptionStartDate = subscriptionStartDate;
        this.subscriptionEndDate = subscriptionEndDate;
        this.adminName = adminName;
        this.isSubscribed = isSubscribed;
        this.adminPassword = adminPassword;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getSubscriptionStartDate() {
        return subscriptionStartDate;
    }

    public void setSubscriptionStartDate(java.util.Date subscriptionStartDate) {
        this.subscriptionStartDate = subscriptionStartDate;
    }

    public java.util.Date getSubscriptionEndDate() {
        return subscriptionEndDate;
    }

    public void setSubscriptionEndDate(java.util.Date subscriptionEndDate) {
        this.subscriptionEndDate = subscriptionEndDate;
    }

    public String getAdminName() {
        return adminName;
    }

    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    public Boolean getIsSubscribed() {
        return isSubscribed;
    }

    public void setIsSubscribed(Boolean isSubscribed) {
        this.isSubscribed = isSubscribed;
    }

    public String getAdminPassword() {
        return adminPassword;
    }

    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }

}
